第十回課題
iijima-pixcel/RaiseTech pull request #4
Opened 2023-11-01 12:38 UTC by iijima-pixcel

new file:   img/lesson10/l10albsecurity.png
	new file:   img/lesson10/l10albtarget.png
	new file:   img/lesson10/l10ap-stack-source.png
	new file:   img/lesson10/l10ec2.png
	new file:   img/lesson10/l10ec2security.png
	new file:   img/lesson10/l10net-stack-source.png
	new file:   img/lesson10/l10rds.png
	new file:   img/lesson10/l10rdssecurity.png
	new file:   img/lesson10/l10s3.png
	new file:   img/lesson10/l10security-stack-source.png
	new file:   img/lesson10/l10vpc.png
	new file:   l10cloud-formation/lesson10ap.yml
	new file:   l10cloud-formation/lesson10network.yml
	new file:   l10cloud-formation/lesson10security.yml
	new file:   lesson10.md

2023-11-02 14:38 UTC, MasatoshiMizumoto requested changes
しっかり設計実装できていると思います！
いくつかコメント入れましたのでご対応お願いします！！

2023-11-02 14:38 UTC, MasatoshiMizumoto commented on l10cloud-formation/lesson10security.yml
> +          CidrIp: 121.105.112.83/32
インバウンドのソースIPは恐らくご自身のインターネットパブリックIPかなと理解しましたので、ここは固定値にしないほうが良いかなと思います！
```suggestion
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref CiderIpFromInernet
```

2023-11-02 14:38 UTC, MasatoshiMizumoto commented on l10cloud-formation/lesson10network.yml
> +
最終行に改行がない警告が出ているのでファイルを調査＆修正ください！

2023-11-02 14:38 UTC, MasatoshiMizumoto commented on l10cloud-formation/lesson10security.yml
> +
こちらも最終行に改行がない警告が出ているのでファイルを調査＆修正ください！

2023-11-02 14:38 UTC, MasatoshiMizumoto commented on l10cloud-formation/lesson10ap.yml
> +            - !ImportValue l10ec2securityoutName
命名規則がケバブケース、ローワーキャメルケース、パスカルケースどれなのか読み取れなかったので、れにするかは決めた方が良いかなと思います！
例えばローワーキャメルケースだとこう表現します！
```suggestion
            - !ImportValue l10Ec2SecurityOutName
```

2023-11-02 14:38 UTC, MasatoshiMizumoto commented on l10cloud-formation/lesson10ap.yml
> +            - !ImportValue l10ec2securityoutName
私が指摘した部分以外も関係する話ですので、命名規則を決定したら規則に則って全て修正ください！

2023-11-02 14:38 UTC, MasatoshiMizumoto commented on l10cloud-formation/lesson10network.yml
> +      Name: public1aoutName
このOutputの書き方だと、中にID(subnet-12345678abcd)が入っているのか、名称（public1al10）が入っているのかExportNameだけみて判断しようとすると誤解するかなと思ったのですが、格納されているのは名称でよかったですか？

2023-11-06 00:36 UTC, iijima-pixcel commented on l10cloud-formation/lesson10security.yml
> +          CidrIp: 121.105.112.83/32
Statusの項目を作り、参照させるようにしました

2023-11-06 00:55 UTC, iijima-pixcel commented on l10cloud-formation/lesson10network.yml
> +      Name: public1aoutName
中には論理idが入っているので、ExportNameにIdを入れて変更しました

2023-11-06 01:45 UTC, iijima-pixcel commented on l10cloud-formation/lesson10network.yml
> +
警告は赤いマイナスマークのことで合っていたでしょうか？
vscodeで作っていたため、改行コードをLFに変更し、ファイル末尾に自動的に改行を挿入する設定にしました。

2023-11-06 01:45 UTC, iijima-pixcel commented on l10cloud-formation/lesson10ap.yml
> +            - !ImportValue l10ec2securityoutName
命名規則をローワーキャメルケースに統一しました。ただし、s3は大文字を使えないため、小文字のままです。

2023-11-06 06:30 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-11-06 09:18 UTC, merged